### ISSUE TITLE
Improper Token

### ISSUE THREAD

**Issue by Barryloa** [adrianaryaputra/discordbot-pokemeow#8]
Hello. Yesterday i tested the bot and it was working but now i can't launch it anymore when i put my token it's say "Improper token has been passed" i don't understand why could you help me ? Thanks :)

![image_2021-10-05_063005](https://user-images.githubusercontent.com/91901678/135960253-9ebfc8bd-5c38-4901-943c-acf1737a9ea9.png)

**Comment by adrianaryaputra** [comment]
Yes, the token is expires..
You need to obtain a new one

**Comment by Barryloa** [comment]
yeah but i try with the new one like 10 times and still don't work

**Comment by Barryloa** [comment]
Thanks it was the python version now it's all good.
